/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nara_beehive_util_jni_Chown */

#ifndef _Included_com_nara_beehive_util_jni_Chown
#define _Included_com_nara_beehive_util_jni_Chown
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nara_beehive_util_jni_Chown
 * Method:    chown
 * Signature: (Ljava/lang/String;II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_nara_beehive_util_jni_Chown_chown
  (JNIEnv *, jobject, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
