/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nara_beehive_util_jni_Copy */

#ifndef _Included_com_nara_beehive_util_jni_Copy
#define _Included_com_nara_beehive_util_jni_Copy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nara_beehive_util_jni_Copy
 * Method:    copy
 * Signature: (Ljava/lang/String;Ljava/lang/String;)
 */
JNIEXPORT jboolean JNICALL Java_com_nara_beehive_util_jni_Copy_copy
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
