/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nara_beehive_util_jni_Dir */

#ifndef _Included_com_nara_beehive_util_jni_Dir
#define _Included_com_nara_beehive_util_jni_Dir
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nara_beehive_util_jni_Dir
 * Method:    list
 * Signature: (Ljava/lang/String;I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_nara_beehive_util_jni_Dir_list
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
