/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nara_beehive_util_jni_Crypt */

#ifndef _Included_com_nara_beehive_util_jni_Crypt
#define _Included_com_nara_beehive_util_jni_Crypt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nara_beehive_util_jni_Crypt
 * Method:    verifyPassword
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_nara_beehive_util_jni_Crypt_verifyPassword
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
